name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.23.2"

      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Define FILE_NAME
        run: echo "FILE_NAME=infratoolbox-${{ env.TAG_NAME }}-macos.tar.gz" >> $GITHUB_ENV

      - name: Build
        run: |
          go mod init github.com/dainer88/infratoolbox
          go mod tidy
          GOOS=darwin GOARCH=amd64 go build -o infratoolbox
          tar -cvzf ${{ env.FILE_NAME }} infratoolbox

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: ${{ env.FILE_NAME }}

  create-release-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.23.2"
      
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Define FILE_NAME
        run: echo "FILE_NAME=infratoolbox-${{ env.TAG_NAME }}-linux.tar.gz" >> $GITHUB_ENV

      - name: Build
        run: |
          go mod init github.com/dainer88/infratoolbox
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o infratoolbox
          tar -cvzf ${{ env.FILE_NAME }} infratoolbox

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: ${{ env.FILE_NAME }}

  create-release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.23.2"
      
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Define FILE_NAME
        run: echo "FILE_NAME=infratoolbox-${{ env.TAG_NAME }}-windows.zip" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: |
          go mod init github.com/dainer88/infratoolbox
          go mod tidy
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o infratoolbox.exe
          $fileName = $env:FILE_NAME
          Compress-Archive -Path infratoolbox.exe -DestinationPath $fileName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: ${{ env.FILE_NAME }}

  create-github-release:
    runs-on: ubuntu-latest
    needs: [create-release-macos, create-release-linux, create-release-windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-binary
          path: .

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: .

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: .
      
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Get changelog entry
        id: get_changelog
        run: |
          NOTES=$(awk '/^## /{if (p) exit; p=1; next} p' CHANGELOG.md)
          echo "${NOTES}" > release_notes.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            infratoolbox-${{ env.TAG_NAME }}-macos.tar.gz
            infratoolbox-${{ env.TAG_NAME }}-linux.tar.gz
            infratoolbox-${{ env.TAG_NAME }}-windows.zip
          body_path: ./release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew-formula:
    runs-on: ubuntu-latest
    needs: create-github-release

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_REPO_CLIENTID }}
          private-key: ${{ secrets.GH_APP_REPO_SECRET }}
      
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: master
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-binary
          path: .
  
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Calculate SHA256
        id: sha256
        run: |
          echo "SHA256=$(shasum -a 256 infratoolbox-${{ env.TAG_NAME }}-macos.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV
      
      - name: Update Homebrew Formula
        run: |
          sed -i.bak "s|url \".*\"|url \"https://github.com/dainer88/infratoolbox/releases/download/${{ env.TAG_NAME }}/infratoolbox-${{ env.TAG_NAME }}-macos.tar.gz\"|" infratoolbox.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" infratoolbox.rb
          sed -i.bak "s|version \".*\"|version \"${{ env.TAG_NAME }}\"|" infratoolbox.rb
      
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git add infratoolbox.rb
          git commit -m "Update Homebrew formula for version ${{ env.TAG_NAME }}"
          git push origin master
